#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
        max_arr=list(arr)
        min_arr=list(arr)
        i=max(max_arr)
        j=min(min_arr)
        max_arr.remove(j)
        min_arr.remove(i)
        print(sum(min_arr),end=" ")
        print(sum(max_arr))

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
