#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    ch=s[-2:]
    if ch=='AM':
        if s[:2]=='12':
            result=s.replace('12','00')
            return result[:-2]
        else:
            return s[:-2]
    else:
         if s[:2]=='12':
            return s[:-2]
         else:
            hr=s[:2]
            time=int(hr)+12
            final=s.replace(hr,str(time))
            return final[:-2]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
